### ISSUE TITLE
Add delete button to individual cross page

### ISSUE THREAD

**Issue by trife** [PhenoApps/Intercross#10]

**Comment by chaneylc** [comment]
Added delete button to cross entry page in commit: 1cce0c406dec931a6a8ff0dfbcce30462a1b6f2e

**Comment by trife** [comment]
Move to toolbar

**Comment by chaneylc** [comment]
Moved the delete button to the toolbar in commit: 2cc88f8e41819cec2f5deb0d8638b67d88d941e9

**Comment by trife** [comment]
Add a single confirmation dialog before delete

**Comment by chaneylc** [comment]
A confirmation dialog was added.
