### ISSUE TITLE
Add about dialog

### ISSUE THREAD

**Issue by trife** [PhenoApps/Intercross#16]
about:
https://github.com/daniel-stoneuk/material-about-library

include aboutLibraries:
https://github.com/mikepenz/AboutLibraries

**Comment by trife** [comment]
https://github.com/PhenoApps/Field-Book/blob/master/app/src/main/java/com/fieldbook/tracker/activities/AboutActivity.java

**Comment by chaneylc** [comment]
About dialog has been added, some information needs to be changed.
