### ISSUE TITLE
Add Firebase analytics

### ISSUE THREAD

**Issue by trife** [PhenoApps/Intercross#17]

**Comment by chaneylc** [comment]
Please send me the google_services.json

**Comment by trife** [comment]
We'll want to add analytics and crashlytics:

`implementation 'com.google.firebase:firebase-analytics:17.2.2'`
`implementation 'com.google.firebase:firebase-crashlytics:17.0.0'`

[google-services.zip](https://github.com/PhenoApps/Intercross/files/4730604/google-services.zip)
