### ISSUE TITLE
Database export/import option

### ISSUE THREAD

**Issue by trife** [PhenoApps/Intercross#23]

**Comment by trife** [comment]
- Move database import/export to a "Database" section in the settings

**Comment by trife** [comment]
@chaneylc are there any sharedpreferences that also need to be exported along with the .db file? If so it would be great to bundle these into a single zip file.

**Comment by chaneylc** [comment]
I went ahead and merged this into develop from commit db215f1dbb140cac5a88c91c78b7d85343ddb67f
