### ISSUE TITLE
Add ability to set default metadata values

### ISSUE THREAD

**Issue by trife** [PhenoApps/Intercross#32]

**Comment by trife** [comment]
Metadata creation and defaults should live in a Settings section instead of within each individual cross.

**Comment by trife** [comment]
Is it possible to set defaults for the three default metadata fields?

**Comment by chaneylc** [comment]
@trife right now you would have to long-press the field, delete it, and recreate it with the default value you want.

**Comment by trife** [comment]
Yeah that's not a great way to handle things. I think the metadata manager in the settings should be allow the standard metadata fields to be assigned defaults as well.

**Comment by chaneylc** [comment]
Ok I adjusted the preferences to allow updating default values.
