### ISSUE TITLE
Add / Implement option to config printer on settings page

### ISSUE THREAD

**Issue by fruizlanders** [PhenoApps/Intercross#66]
Please help us (CIP) printing. We have already check printer settings and it was set as it is told on the manual.

**Comment by trife** [comment]
What printer model are you using and what difficulties are you running into?

I think many of the printer settings are handled from the Zebra Print Connect app.

**Comment by fruizlanders** [comment]
Hi Trevor,

ZQ510.
I can create crosses and even specify seeds or flowers, for instance, but
then it prints all the data in one line except parents name.
even QR code gets printed oddly.
Have you run into some trouble with the zebra printer? If so, did you only
figure out those issues with Zebra Print Connect or Zebra Printer
Utilities? Or maybe you could give us some hints on zpl programming.

I belong to the IPC and you can contact me at ***@***.***

Best,

Franco Ruz
[image: Image]
