### ISSUE TITLE
Parents list import fails with error: "Missing headers in import file: codeID"

### ISSUE THREAD

**Issue by conjon42** [PhenoApps/Intercross#73]
Importing parents list from local storage on Android fails with the error: "Missing headers in import file: codeID." Failure occurs even when trying to import the example list of parents included with the app data. Importing on Pixel 6 with .csv files made in Microsoft Excel.

**Comment by trife** [comment]
Can you upload or email me the list of parents you're trying to import?

**Comment by ahsanasif86** [comment]
Hi 

I am having the same issue. Attached are the sample file that I have been trying to upload. 
[Cross list.csv](https://github.com/PhenoApps/Intercross/files/14859616/Cross.list.csv)
[Crossing.csv](https://github.com/PhenoApps/Intercross/files/14859617/Crossing.csv)

**Comment by trife** [comment]
I think this is fixed in v2 which should be released soon.
