### ISSUE TITLE
Linebreaks in exported CSV

### ISSUE THREAD

**Issue by noahddewitt** [PhenoApps/Intercross#76]
Exported CSV shows line breaks in exported CSV that do not appear in the cross view within the app:

![thumbnail_Screenshot_20240202-111029](https://github.com/PhenoApps/Intercross/assets/82885768/b23927ed-c350-4770-9e7e-d65e4b55b65d)

![image](https://github.com/PhenoApps/Intercross/assets/82885768/b5efab6a-59ca-4552-82eb-5969b755359b)

Line breaks appear after crosser field, and are only associated with a single crosser name (JS). This issue does not appear with other times that crosser name "JS" has been input, so it may be the result of a mis-click or special character entry in the crosser field in the settings? Issue was resolved by deleting those specific crosses from the app.

**Comment by trife** [comment]
We're unable to recreate the issue. If the problem reoccurs we can reopen this.
