### ISSUE TITLE
Template files

### ISSUE THREAD

**Issue by ahsanasif86** [PhenoApps/Intercross#81]
Hi 

Just wondering if you could provide me the template files to import the crossing list.

Thanks

**Comment by chaneylc** [comment]
Wishlist, parents, and crossing list examples can be found [here](https://github.com/PhenoApps/Intercross/tree/master/app/src/main/res/raw). Let me know if you need more information about each.

**Comment by ahsanasif86** [comment]
Great. Thanks for all the details.
