### ISSUE TITLE
Tags 

### ISSUE THREAD

**Issue by ahsanasif86** [PhenoApps/Intercross#82]
Hi 

Looking for recommendation of tag size/type to be printed with Zebra printer. Would be great if someone can share any photos of printed tags.

Thanks

**Comment by chaneylc** [comment]
Right now we use 2in wide by 1in height tags on a Zebra ZQ510 printer which uses 8dots/mm

**Comment by ahsanasif86** [comment]
Thanks for the details. Can we print small tags (1in x 1in) with Zebra ZQ510

**Comment by chaneylc** [comment]
Yes, you can import a ZPL file from the settings page, which has more information on how to do so.

**Comment by ahsanasif86** [comment]
Great. Thanks for all the details.
